/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
    eclipse
    idea
}

repositories {
    mavenCentral()
    flatDir {
        dirs("lib")
    }
}

dependencies {

    implementation("com.solacesystems:sol-jcsmp:10.19+")
    implementation("org.json:json:20230227")

    implementation("org.apache.logging.log4j:log4j-api:2.19+")
    implementation("org.apache.logging.log4j:log4j-core:2.19+")
    // needed to 'bridge' the JCSMP API logs from JCL to log4j
    implementation("org.apache.logging.log4j:log4j-jcl:2.19.0")
    
    implementation(fileTree(mapOf("dir" to "lib", "include" to listOf("*.jar"))))

}


sourceSets {
    main {
        java {
            srcDir("src/main/java")
            srcDir("src/dist/config")  // so eclipse can find the log4j2.xml file
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.solace.labs.aaron.PrettyDump")
}
